from typing import List, Optional, Literal
from pydantic import BaseModel, Field

class Message(BaseModel):
    role: Literal["user", "assistant", "system"] = Field(
        description="Role of the sender (e.g., 'user', 'assistant', 'system')"
    )
    content: str = Field(description="The actual text content of the message")

class RetrievedChunk(BaseModel):
    chunk_id: str = Field(description="Unique identifier for the text chunk")
    file_name: str = Field(description="Name of the source file")
    text: str = Field(description="The actual text content extracted from the document")
    page: Optional[int] = Field(default=None, description="Page number where the chunk was found (can be null)")

class Citation(BaseModel):
    span: str = Field(description="The specific text span in the generated answer")
    source_file: str = Field(description="Name of the source file")
    chunk_id: str = Field(description="ID of the chunk used for this citation")
    page: Optional[int] = Field(default=None, description="Page number of the citation (can be null)")

class Task(BaseModel):
    task_id: str = Field(description="Unique identifier for the task (e.g., 'task_1')")
    description: str = Field(description="Detailed description of what needs to be done. Must be highly specific and self-contained.")
    task_type: Literal["vector_search", "structured_db_lookup", "general_synthesis"] = Field(
        description="The type of action required to complete this task"
    )
    target_domain: Optional[Literal["HR", "IT"]] = Field(
        default=None, 
        description="The specific domain focused on for this task"
    )
    status: Literal["pending", "in_progress", "completed", "failed"] = Field(
        default="pending", 
        description="Current execution status of the task"
    )
    result_summary: Optional[str] = Field(
        default=None, 
        description="A concise summary of the result after the task is executed. Used for context in subsequent tasks."
    )

class AgentState(BaseModel):
    # 1. Conversation History
    messages: List[Message] = Field(
        default_factory=list, 
        description="Array of chat messages (User query, Assistant replies)"
    )
    
    # 2. Orchestration & Budget
    next_agent: Optional[str] = Field(
        default=None, 
        description="Determines the next agent in the execution graph (e.g., 'Supervisor', 'Retrieval_Agent', or 'END')"
    )
    step_count: int = Field(
        default=0, 
        description="An integer tracking execution steps to enforce a strict reasoning budget/cap"
    )
    
    # 3. Security & Access Control
    allowed_domains: List[str] = Field(
        default_factory=list, 
        description="List of domains the user is authenticated to access (e.g., ['HR', 'IT'])"
    )
    
    # 4. Semantic Classification 
    query_intent: Optional[Literal["chitchat", "out_of_domain", "information_retrieval"]] = Field(
        default=None,
        description="Classification of the user's overall query to route simple queries immediately."
    )
    
    # 5. Dynamic Re-planning 
    tasks: List[Task] = Field(
        default_factory=list, 
        description="List of all tasks (pending, completed, failed) generated by the Planner"
    )
    current_task_id: Optional[str] = Field(
        default=None,
        description="The ID of the task currently being executed by the specialist agents"
    )
    
    # 6. Retrieved Data & Context
    retrieved_context: List[RetrievedChunk] = Field(
        default_factory=list, 
        description="An array holding the text chunks and metadata fetched by the retrieval agents"
    )
    is_context_valid: Optional[bool] = Field(
        default=None, 
        description="A boolean set by the Verification agent indicating if the retrieved data answers the current task"
    )
    verification_feedback: Optional[str] = Field(
        default=None, 
        description="Critique generated if is_context_valid is false, used to trigger re-queries"
    )
    
    # 7. Final Output
    citations: Optional[List[Citation]] = Field(
        default=None, 
        description="Mapping of answer spans to source file names and chunk IDs"
    )