from typing import List, Optional
from pydantic import BaseModel, Field

class Message(BaseModel):
    role: str = Field(description="Role of the sender (e.g., 'user', 'assistant')")
    content: str = Field(description="The actual text content of the message")

class RetrievedChunk(BaseModel):
    chunk_id: str = Field(description="Unique identifier for the text chunk")
    file_name: str = Field(description="Name of the source file")
    text: str = Field(description="The actual text content extracted from the document")
    page: Optional[int] = Field(default=None, description="Page number where the chunk was found (can be null)")

class Citation(BaseModel):
    span: str = Field(description="The specific text span in the generated answer")
    source_file: str = Field(description="Name of the source file")
    chunk_id: str = Field(description="ID of the chunk used for this citation")
    page: Optional[int] = Field(default=None, description="Page number of the citation (can be null)")

class AgentState(BaseModel):
    messages: List[Message] = Field(
        default_factory=list, 
        description="Array of chat messages (User query, Assistant replies)"
    )
    next_agent: Optional[str] = Field(
        default=None, 
        description="Determines the next agent in the execution graph (e.g., 'Supervisor', 'Retrieval_Agent', or 'END')"
    )
    step_count: int = Field(
        default=0, 
        description="An integer tracking execution steps to enforce a strict reasoning budget/cap"
    )
    allowed_domains: List[str] = Field(
        default_factory=list, 
        description="List of domains the user is authenticated to access (e.g., ['HR', 'IT'])"
    )
    target_domain: Optional[str] = Field(
        default=None, 
        description="The specific domain focused on for the current sub-task"
    )
    plan: Optional[List[str]] = Field(
        default=None, 
        description="A list of decomposed tasks generated by the planning agent"
    )
    retrieved_context: List[RetrievedChunk] = Field(
        default_factory=list, 
        description="An array holding the text chunks and metadata fetched by the retrieval agents"
    )
    is_context_valid: Optional[bool] = Field(
        default=None, 
        description="A boolean set by the Verification agent indicating if the retrieved data answers the query"
    )
    verification_feedback: Optional[str] = Field(
        default=None, 
        description="Critique generated if is_context_valid is false, used to trigger re-queries"
    )
    citations: Optional[List[Citation]] = Field(
        default=None, 
        description="Mapping of answer spans to source file names and chunk IDs"
    )
