from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field

class Message(BaseModel):
    role: str = Field(description="Role of the sender (e.g., 'user', 'assistant')")
    content: str = Field(description="The actual text content of the message")

class RetrievedChunk(BaseModel):
    chunk_id: str = Field(description="Unique identifier for the text chunk")
    file_name: str = Field(description="Name of the source file")
    text: str = Field(description="The actual text content extracted from the document")
    page: Optional[int] = Field(default=None, description="Page number where the chunk was found (can be null)")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional metadata about the chunk")
    score: Optional[float] = Field(default=None, description="Retrieval score")

class Citation(BaseModel):
    span: str = Field(description="The specific text span in the generated answer")
    source_file: str = Field(description="Name of the source file")
    chunk_id: str = Field(description="ID of the chunk used for this citation")
    page: Optional[int] = Field(default=None, description="Page number of the citation (can be null)")

class Task(BaseModel):
    task_id: str = Field(description="Unique identifier for the task")
    description: str = Field(description="Clear description of the search or lookup task")
    task_type: str = Field(description="Must be either 'vector_search' or 'structured_db_lookup'")
    target_domain: str = Field(description="Target domain, e.g., 'HR' or 'IT'")
    is_dependent: bool = Field(default=False, description="True if this task depends on the success of previous tasks")
    status: str = Field(default="pending", description="Status of the task: 'pending', 'in_progress', 'completed', 'failed', 'skipped'")
    result_summary: Optional[str] = Field(default=None, description="Summary of the retrieval or DB lookup after task completion")

class AgentState(BaseModel):
    messages: List[Message] = Field(
        default_factory=list, 
        description="Array of chat messages (User query, Assistant replies)"
    )
    next_agent: Optional[str] = Field(
        default=None, 
        description="Determines the next agent in the execution graph (e.g., 'Supervisor', 'Retrieval_Agent', or 'END')"
    )
    step_count: int = Field(
        default=0, 
        description="An integer tracking execution steps to enforce a strict reasoning budget/cap"
    )
    allowed_domains: List[str] = Field(
        default_factory=list, 
        description="List of domains the user is authenticated to access (e.g., ['HR', 'IT'])"
    )
    target_domain: Optional[str] = Field(
        default=None, 
        description="The specific domain focused on for the current sub-task"
    )
    username: Optional[str] = Field(
        default=None,
        description="The authenticated username of the user making the query"
    )
    
    # ---------------------------------------------------------
    # New Fields for Dynamic Re-planning (ReAct)
    # ---------------------------------------------------------
    query_intent: Optional[str] = Field(
        default=None, 
        description="Intent of the current query: 'casual_chat', 'information_retrieval', 'ready_for_synthesis'"
    )
    tasks: List[Task] = Field(
        default_factory=list, 
        description="A dynamic list of decomposed tasks generated and updated iteratively by the planning agent"
    )
    current_task_id: Optional[str] = Field(
        default=None, 
        description="The ID of the task currently being executed"
    )
    # ---------------------------------------------------------

    retrieved_context: List[RetrievedChunk] = Field(
        default_factory=list, 
        description="An array holding the text chunks and metadata fetched by the retrieval agents"
    )
    is_context_valid: Optional[bool] = Field(
        default=None, 
        description="A boolean set by the Verification agent indicating if the retrieved data answers the query"
    )
    verification_feedback: Optional[str] = Field(
        default=None, 
        description="Critique generated if is_context_valid is false, used to trigger re-queries"
    )
    citations: Optional[List[Citation]] = Field(
        default=None, 
        description="Mapping of answer spans to source file names and chunk IDs"
    )
    answer: Optional[str] = Field(
        default=None,
        description="Final answer generated by the system"
    )
    # داخل ملف state.py أضف هذا الحقل لـ AgentState
    conversation_summary: Optional[str] = Field(
    default="",
    description="A running summary of the conversation history to maintain long-term context."
)